"""Initial migration - create tables

Revision ID: 8e07428053da
Revises: 
Create Date: 2025-01-31 09:05:17.210528+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e07428053da'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_resources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('publication_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_resources_author'), 'content_resources', ['author'], unique=False)
    op.create_index(op.f('ix_content_resources_id'), 'content_resources', ['id'], unique=False)
    op.create_index(op.f('ix_content_resources_title'), 'content_resources', ['title'], unique=False)
    op.create_index(op.f('ix_content_resources_url'), 'content_resources', ['url'], unique=True)
    op.create_table('system_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('total_ratings', sa.Integer(), nullable=True),
    sa.Column('cache_stats', sa.JSON(), nullable=True),
    sa.Column('avg_processing_time', sa.Float(), nullable=True),
    sa.Column('active_since', sa.DateTime(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_stats_id'), 'system_stats', ['id'], unique=False)
    op.create_table('content_metadata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content_id', sa.Integer(), nullable=True),
    sa.Column('keywords', sa.JSON(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.Column('avg_interaction_time', sa.Float(), nullable=True),
    sa.Column('social_shares', sa.Integer(), nullable=True),
    sa.Column('total_interactions', sa.Integer(), nullable=True),
    sa.Column('citations', sa.Integer(), nullable=True),
    sa.Column('author_credentials_score', sa.Float(), nullable=True),
    sa.Column('domain_authority', sa.Float(), nullable=True),
    sa.Column('positive_outcomes', sa.Integer(), nullable=True),
    sa.Column('conversion_rate', sa.Float(), nullable=True),
    sa.Column('user_satisfaction', sa.Float(), nullable=True),
    sa.Column('review_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['content_id'], ['content_resources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_metadata_category'), 'content_metadata', ['category'], unique=False)
    op.create_index(op.f('ix_content_metadata_id'), 'content_metadata', ['id'], unique=False)
    op.create_table('ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content_id', sa.Integer(), nullable=True),
    sa.Column('resource_id', sa.String(), nullable=True),
    sa.Column('final_score', sa.Float(), nullable=True),
    sa.Column('rating_timestamp', sa.DateTime(), nullable=True),
    sa.Column('rating_metadata', sa.JSON(), nullable=True),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.Column('authority_score', sa.Float(), nullable=True),
    sa.Column('engagement_score', sa.Float(), nullable=True),
    sa.Column('clarity_score', sa.Float(), nullable=True),
    sa.Column('impact_score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['content_id'], ['content_resources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ratings_id'), 'ratings', ['id'], unique=False)
    op.create_index(op.f('ix_ratings_resource_id'), 'ratings', ['resource_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ratings_resource_id'), table_name='ratings')
    op.drop_index(op.f('ix_ratings_id'), table_name='ratings')
    op.drop_table('ratings')
    op.drop_index(op.f('ix_content_metadata_id'), table_name='content_metadata')
    op.drop_index(op.f('ix_content_metadata_category'), table_name='content_metadata')
    op.drop_table('content_metadata')
    op.drop_index(op.f('ix_system_stats_id'), table_name='system_stats')
    op.drop_table('system_stats')
    op.drop_index(op.f('ix_content_resources_url'), table_name='content_resources')
    op.drop_index(op.f('ix_content_resources_title'), table_name='content_resources')
    op.drop_index(op.f('ix_content_resources_id'), table_name='content_resources')
    op.drop_index(op.f('ix_content_resources_author'), table_name='content_resources')
    op.drop_table('content_resources')
    # ### end Alembic commands ###
