"""add_file_support_columns

Revision ID: 93635b805d75
Revises: 8e07428053da
Create Date: 2025-01-31 11:12:33.842799+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93635b805d75'
down_revision: Union[str, None] = '8e07428053da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('content_resources', sa.Column('raw_content', sa.String(), nullable=True))
    op.add_column('content_resources', sa.Column('file_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('content_resources', 'file_type')
    op.drop_column('content_resources', 'raw_content')
    # ### end Alembic commands ###
